### ISSUE TITLE
package for Linux

### ISSUE THREAD

**Issue by kannono1** [kannono1/kafx#4]

**Comment by kannono1** [comment]
linux

**Comment by kannono1** [comment]
```
deployment:
  production:
    branch: master
    commands:
      - bundle exec cap production deploy
```
